# Matrices
#### Two-dimensional array of numbers
#### Denoted in uppercase, italics and bold
#### Height given priority ahead of width in notation,i.e. (nrow, ncol)
#### . If x has three rows and two columns, it shape is (3,2)
#### Individual scalar elements denoted in uppercase, italics only
#### . Elements in top-right corner of matrix X above would be X(1,2)
#### Colon represents an entire row or column:
#### . Left column of matrix X ix X:,1
#### . Right column of matrix X is X:,2
#### . Middle row of matrix X is X2,:


# Code

In [1]:
import numpy as np

In [3]:
X = np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [4]:
X.shape

(3, 2)

In [5]:
X.size

6

In [6]:
# Select left column of matrix X (zero-indexed)
X[:,0]

array([25,  5,  3])

In [9]:
# Select middle row of matrix X:
X[1,:]

array([ 5, 26])

In [12]:
# Right column of matrix X
X[:, 1]

array([ 2, 26,  7])

In [18]:
# Another slicing-by-index example:
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

# Matrices in PyTorch



In [21]:
import torch

In [22]:
import tensorflow as tf

In [23]:
X_pt = torch.tensor([[25,2],[5,26],[3,7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [24]:
X_pt.shape # more pythonic

torch.Size([3, 2])

In [25]:
X_pt[1,:]

tensor([ 5, 26])

# Matrices in TensorFlow

In [26]:
X_tf = tf.Variable([[25,2],[5,26],[3,7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [27]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [28]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [29]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>