# Norms
#### Norms are functions that quantify vector magnitude.

## L2 Norms
#### Measures simple(Euclidean) distance from origin
#### Most common norm in machine learning
#### L2 Norms are sensitive to outliers 

## Code

In [1]:
import numpy as np

In [2]:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [3]:
(25**2 + 2**2 + 5**2)** (1/2)

25.573423705088842

In [4]:
np.linalg.norm(x)

25.573423705088842

##### So, if units in this dimension vector space are meters, then the vectors x has a length of 25.6m.


## Unit Vectors
#### Special case of vector where its length is equal to one
#### Technically, x is a unit vector with "unit norm", i.e.: ||x|| = 1

## L1 Norm

#### Common norm in ML
#### Varies linearly at all locations whether near or far from origin
#### Used whenever difference between zero and non-zero is key


## Code

In [5]:
x

array([25,  2,  5])

In [6]:
np.abs(25) + np.abs(2) + np.abs(5) # absolute value of each of the element

32

## Squared L2 Norm

#### Computationally cheaper to use than l2 norm because:
#### . Squared l2 norm equals simply x^Tx
#### . Derivative(used to train many ML algorithm) of element x requires that element alone, whereas L2 norm requires x vector
#### . Downside is it grows alowly near origin so can't be used if distinguishing between zero and near-zero is important it means L1 norms excels  at distinguishing between them.



In [7]:
x

array([25,  2,  5])

In [8]:
(25**2 + 2**2 + 5**2)

654

In [9]:
# We will cover tensor multiplication more soon but toprove point quickly:
np.dot(x,x)

654

## Max Morm or ( L infinity Norm)

In [10]:
x

array([25,  2,  5])

In [11]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

## Generalized L^p Norm

In [13]:
x

array([25,  2,  5])

In [15]:
# if p =2
(((np.abs(25)+ np.abs(2) + np.abs(5))) ** 2 ) **(1/2)

32.0