# Vectors in NumPy

In [1]:
import numpy as np

In [4]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [5]:
len(x)

3

In [6]:
x.shape

(3,)

In [7]:
type(x)

numpy.ndarray

In [8]:
x[0] # zero-indexed

25

In [11]:
type(x[0])

numpy.int32

## Vector Transposition

In [12]:
# Transposing a regular 1-D aray has no effect...
x_t = x.T # .T= add onto the end of any given vectors and it will transpose it for us.
x_t

array([25,  2,  5])

In [13]:
x_t.shape

(3,)

In [14]:
# ...but it does when we use nested "matrix-style" brackets:
y = np.array([[25,2,5]])
y


array([[25,  2,  5]])

In [15]:
y.shape

(1, 3)

In [16]:
# ...but can transpose a matrix with a dimension of length 1, which is mathematically equivalent:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [17]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [23]:
# column vector can be transposed back to original row vector:
y_t.T

array([[25,  2,  5]])

In [24]:
y_t.T.shape

(1, 3)

# Zero Vectors

In [26]:
z = np.zeros(3)
z

array([0., 0., 0.])

# Vectors in PyTorch and TensorFlow

In [28]:
import torch

In [29]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [30]:
import tensorflow as tf

In [31]:
x_tf = tf.Variable([25,2,5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>